name: Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK (for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use Java 11 or higher
        distribution: 'zulu'  # Use Zulu for OpenJDK distribution

    - name: Install JMeter
      run: |
        # Download JMeter
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        
        # Verify download success
        if [ ! -f apache-jmeter-5.6.3.tgz ]; then
          echo "JMeter tarball download failed"
          exit 1
        fi

        echo "Download Successful. Now Extracting..."

        # Extract JMeter
        tar -xvzf apache-jmeter-5.6.3.tgz
        
        # Verify extraction success
        if [ ! -d apache-jmeter-5.6.3 ]; then
          echo "JMeter extraction failed"
          exit 1
        fi
        
        echo "JMeter extracted successfully. Listing extracted files..."
        ls -l apache-jmeter-5.6.3  # Show the extracted files to ensure it's correct

        # Move JMeter to the expected directory
        mv apache-jmeter-5.6.3 /home/runner/jmeter

    - name: List extracted JMeter folder contents
      run: |
        echo "Listing contents of /home/runner/jmeter"
        ls -l /home/runner/jmeter

    - name: List contents of JMeter bin directory
      run: |
        echo "Listing contents of JMeter bin directory"
        ls -l /home/runner/jmeter/apache-jmeter-5.6.3/bin  # This should show the 'jmeter' executable

    - name: Create report directories
      run: |
        mkdir -p ./reports/dashboard
        chmod -R 777 ./reports

   - name: Run JMeter Performance Test
  run: |
    # Adjust path to match the correct directory structure
    /home/runner/jmeter/bin/jmeter -n -t ./test-scripts/sienna_bot.jmx -l ./reports/results.jtl -e -o ./reports/dashboard
