name: Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK (for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use Java 11 or higher
        distribution: 'adoptopenjdk'  # You can also use 'zulu' or 'openjdk' as alternatives

    - name: Create report directories
      run: |
        mkdir -p ./reports/dashboard
        chmod -R 777 ./reports

    - name: Run JMeter Performance Test
      run: |
        ./apache-jmeter-5.6.3/bin/jmeter -n -t ./test-scripts/sienna_bot.jmx -l ./reports/results.jtl -e -o ./reports/dashboard
