name: Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (required for JMeter)
    - name: Set up JDK (for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Use Zulu OpenJDK distribution

    # Step 3: Install and extract JMeter
    - name: Install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz -C /home/runner/
        mv /home/runner/apache-jmeter-5.6.3 /home/runner/jmeter

    # Step 4: Verify JMeter installation
    - name: Verify JMeter Installation
      run: |
        echo "Listing contents of /home/runner/jmeter"
        ls -l /home/runner/jmeter
        echo "Listing contents of JMeter bin directory"
        ls -l /home/runner/jmeter/bin

    # Step 5: Create report directories
    - name: Create report directories
      run: |
        mkdir -p ./reports/dashboard
        chmod -R 777 ./reports

    # Step 6: Run JMeter Performance Test
    - name: Run JMeter Performance Test
      run: |
        /home/runner/jmeter/bin/jmeter -n -t ./test-scripts/sienna_bot.jmx -l ./reports/results.jtl -e -o ./reports/dashboard
