name: Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK (for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use Java 11 or higher
        distribution: 'zulu'  # Use Zulu for OpenJDK distribution

    - name: Install JMeter
      run: |
        # Download JMeter
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        
        # Verify that the file is downloaded
        ls -l apache-jmeter-5.6.3.tgz  # List the downloaded .tgz file
        
        # Extract the JMeter package
        tar -xvzf apache-jmeter-5.6.3.tgz
        
        # Verify extraction by listing the extracted files
        ls -l  # List the extracted files in the current directory
        
        # Move JMeter to the correct directory
        mv apache-jmeter-5.6.3 /home/runner/jmeter

    - name: List extracted JMeter folder contents
      run: |
        ls -l /home/runner/jmeter  # Check if the JMeter folder exists
        
    - name: List contents of JMeter bin directory
      run: |
        ls -l /home/runner/jmeter/apache-jmeter-5.6.3/bin  # Check if the 'jmeter' executable is present

    - name: Create report directories
      run: |
        mkdir -p ./reports/dashboard
        chmod -R 777 ./reports

    - name: Run JMeter Performance Test
      run: |
        /home/runner/jmeter/apache-jmeter-5.6.3/bin/jmeter -n -t ./test-scripts/sienna_bot.jmx -l ./reports/results.jtl -e -o ./reports/dashboard
