name: Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (required for JMeter)
    - name: Set up JDK (for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Use Zulu OpenJDK distribution

    # Step 3: Install and extract JMeter
    - name: Install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz -C /home/runner/
        mv /home/runner/apache-jmeter-5.6.3 /home/runner/jmeter

    # Step 4: Download cmdrunner-2.3.jar
    - name: Download cmdrunner-2.3.jar
      run: |
        wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar -O /home/runner/jmeter/lib/cmdrunner-2.3.jar

    # Step 5: Install JMeter Plugins
    - name: Install JMeter Plugins
      run: |
        wget https://jmeter-plugins.org/get/ -O /home/runner/jmeter/lib/ext/jmeter-plugins-manager.jar
        java -cp /home/runner/jmeter/lib/ext/jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
        # Generate the PluginsManagerCMD.sh script after installation
        cp /home/runner/jmeter/lib/ext/jmeter-plugins-manager.jar /home/runner/jmeter/lib/ext/jmeter-plugins-manager-generated.jar

    # Step 6: Verify JMeter Installation and Plugins
    - name: Verify JMeter Installation and Plugins
      run: |
        echo "Listing contents of /home/runner/jmeter/bin"
        ls -l /home/runner/jmeter/bin
        echo "Listing contents of /home/runner/jmeter/lib/ext"
        ls -l /home/runner/jmeter/lib/ext

    # Step 7: Create report directories
    - name: Create report directories
      run: |
        mkdir -p ./reports/dashboard
        chmod -R 777 ./reports

    # Step 8: Run JMeter Performance Test
    - name: Run JMeter Performance Test
      run: |
        /home/runner/jmeter/bin/jmeter -n -t ./test-scripts/sienna_bot.jmx -l ./reports/results.jtl -e -o ./reports/dashboard
