name: Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK (for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 /home/runner/jmeter

    - name: List JMeter directory contents
      run: |
        ls -R /home/runner/jmeter

    - name: Create report directories
      run: |
        mkdir -p ./reports/dashboard
        chmod -R 777 ./reports

    - name: Run JMeter Performance Test
      run: |
        /home/runner/jmeter/bin/jmeter -n -t ./test-scripts/sienna_bot.jmx -l ./reports/results.jtl -e -o ./reports/dashboard

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: |
          ./reports/results.jtl
          ./reports/dashboard
