name: Performance Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK (for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use Java 11 or higher
        distribution: 'zulu'  # Use Zulu for OpenJDK distribution

    - name: Install JMeter
      run: |
        # Download and unzip JMeter
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 /home/runner/jmeter

    - name: Create report directories
      run: |
        mkdir -p ./reports/dashboard
        chmod -R 777 ./reports

    - name: Run JMeter Performance Test
      run: |
        ./apache-jmeter-5.6.3/bin/jmeter -n -t ./test-scripts/sienna_bot.jmx -l ./reports/results.jtl -e -o ./reports/dashboard
